Neu aufgesetztes Projekt mit SvelteKit für Routing-Fix und neue Kompo…
Doma1612/video-portal-frontend pull request #8
Opened 2023-10-23 13:49 UTC by philippkuehling

- Projekt neu mit SveleKit aufgestezt
- Routing Probleme behoben
- Liniting aktiviert und ignorierende Regeln implementiert 
- neue Komponenten implementiert 
-

2023-10-24 13:38 UTC, Doma1612 requested changes

2023-10-24 13:38 UTC, Doma1612 commented on .eslintrc.cjs
> +};
Warum eine zweite Config mit js? Wir haben doch schon unsere eslintrc.yml

2023-10-24 13:38 UTC, Doma1612 commented on .prettierrc
> +}
Gleiches hier? haben eine prettier yml

2023-10-24 15:42 UTC, philippkuehling commented on .prettierrc
> +}
Moin,

gleiches hier: die sollten nicht mit rein, die waren noch im alten Projekt enthalten. Werden also entfernt.

2023-10-25 15:15 UTC, philippkuehling commented
Moin,

könntet ihr das einmal reviewen? 

Danke!

2023-10-26 09:44 UTC, Doma1612 approved these changes
LGTM!

2023-10-26 09:44 UTC, merged